### ISSUE TITLE
ValueSortedDict.__repr__ throws AttributeError

### ISSUE THREAD

**Issue by ahrzb** [grantjenks/sortedcollections#2]
`
>>> import sortedcollections
>>> v = sortedcollections.ValueSortedDict()
>>> v
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bandbaz/.pyenv/versions/3.6.3/lib/python3.6/site-packages/sortedcontainers/sortedlist.py", line 48, in wrapper
    return func(self)
  File "/home/bandbaz/.pyenv/versions/3.6.3/lib/python3.6/site-packages/sortedcollections/recipes.py", line 177, in __repr__
    repr(self._load),
AttributeError: 'ValueSortedDict' object has no attribute '_load'
`

**Comment by grantjenks** [comment]
Fixed at d12ac25 and released at 0.6.1
